apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      group: gateway
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          group: sandbox
    ports:
    - protocol: TCP
      port: 80
